server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1
            - CircuitBreaker=myCircuitBreaker

        - id: shopping_store_service_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - CircuitBreaker=myCircuitBreaker
            - name: Retry
              args:
                retries: 3
                methods: GET
                statuses: NOT_FOUND
                exceptions:
                  - java.io.IOException
                  - org.springframework.cloud.gateway.support.TimeoutException