server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/paymentDB
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: count_based
        sliding-window-size: 6
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 2
    instances:
      shopping-store:
        baseConfig: default
      order:
        baseConfig: default